version: "3"

services:
  app:
    container_name: ecommerce-laravel
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./ecommerce-laravel/:/var/www/html
    restart: always
    networks: 
      - internal
      - external

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: qPThHm6uKC2C2cS2Dudr6wUd
      MYSQL_ROOT_PASSWORD: MrcD64kvz3aqSQhw2gJQzNYc
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - internal
      - external
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./ecommerce-laravel/:/var/www/html
    working_dir: /var/www/html
    depends_on:
      -ecommerce-laravel

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./ecommerce-laravel/:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./ecommerce-laravel/:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - internal
      - external

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./ecommerce-laravel/:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - app


networks:
  external:
    driver: bridge
  internal:
    driver: bridge


